---
# tasks file for apigee-opdk-portal-os-config
- name: Removed packages known to cause system conflicts with dev portal
  yum:
    name: '{{ item }}'
    state: absent
  with_items:
  - php
  - php-cli
  - php-common
  - php-gd
  - php-mbstring
  - php-mysql
  - php-pdo
  - php-pear
  - php-pecl-apc
  - php-process
  - php-xml